eureka:
  client:
    enabled: true
    serviceUrl:
      #注册中心的地址
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
      - id: admin
        uri: lb://ADMIN-MANAGER
        predicates:
        - Path=/api/v1/admin/**
        filters:
        - StripPrefix=0  #去掉过滤Path路径
      - id: pd_device
        uri: lb://PD-MANAGER
        predicates:
        - Path=/api/v1/device/**
        filters:
        - StripPrefix=1  #去掉过滤Path路径
      - id: pd_product
        uri: lb://PD-MANAGER
        predicates:
        - Path=/api/v1/product/**
        filters:
        - StripPrefix=0  #去掉过滤Path路径
      discovery:
        locator:
          enabled: true
#        filters:
#          - name: RequestRateLimiter
#            args:
#              redis-rate-limiter.replenishRate: 1  # 令牌桶的容积
#              redis-rate-limiter.burstCapacity: 3  # 流速 每秒
#              key-resolver: "#{@userKeyResolver}" #SPEL表达式去的对应的bean
#              rate-limiter: "#{@redisRateLimiter}"
#      - id: xujin_route
#         uri: http://www.xujin.org:80/
#        predicates:
#          - Path=/xujin
#          - Weight=100
#          filters:
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 1  # 令牌桶的容积
#                redis-rate-limiter.burstCapacity: 3  # 流速 每秒
#                key-resolver: "#{@userKeyResolver}" #SPEL表达式去的对应的bean
#                rate-limiter: "#{@redisRateLimiter}"
##                  key-resolver: "#{@userKeyResolver}"
#            - StripPrefix=1

#logging:
#  level:
#    org.springframework.cloud.gateway: TRACE
#    org.springframework.http.server.reactive: info
#    org.springframework.web.reactive: info
#    reactor.ipc.netty: info

feign:
  hystrix:
    enabled: true
